// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "maxPooling.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic maxPooling::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic maxPooling::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<14> maxPooling::ap_ST_fsm_state1 = "1";
const sc_lv<14> maxPooling::ap_ST_fsm_state2 = "10";
const sc_lv<14> maxPooling::ap_ST_fsm_state3 = "100";
const sc_lv<14> maxPooling::ap_ST_fsm_state4 = "1000";
const sc_lv<14> maxPooling::ap_ST_fsm_state5 = "10000";
const sc_lv<14> maxPooling::ap_ST_fsm_state6 = "100000";
const sc_lv<14> maxPooling::ap_ST_fsm_state7 = "1000000";
const sc_lv<14> maxPooling::ap_ST_fsm_state8 = "10000000";
const sc_lv<14> maxPooling::ap_ST_fsm_state9 = "100000000";
const sc_lv<14> maxPooling::ap_ST_fsm_state10 = "1000000000";
const sc_lv<14> maxPooling::ap_ST_fsm_state11 = "10000000000";
const sc_lv<14> maxPooling::ap_ST_fsm_state12 = "100000000000";
const sc_lv<14> maxPooling::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<14> maxPooling::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<32> maxPooling::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> maxPooling::ap_const_lv32_1 = "1";
const sc_lv<32> maxPooling::ap_const_lv32_2 = "10";
const sc_lv<1> maxPooling::ap_const_lv1_0 = "0";
const sc_lv<32> maxPooling::ap_const_lv32_3 = "11";
const sc_lv<32> maxPooling::ap_const_lv32_4 = "100";
const sc_lv<32> maxPooling::ap_const_lv32_5 = "101";
const sc_lv<32> maxPooling::ap_const_lv32_6 = "110";
const sc_lv<32> maxPooling::ap_const_lv32_7 = "111";
const sc_lv<32> maxPooling::ap_const_lv32_8 = "1000";
const sc_lv<32> maxPooling::ap_const_lv32_A = "1010";
const sc_lv<32> maxPooling::ap_const_lv32_B = "1011";
const sc_lv<32> maxPooling::ap_const_lv32_C = "1100";
const sc_lv<32> maxPooling::ap_const_lv32_D = "1101";
const sc_lv<7> maxPooling::ap_const_lv7_0 = "0000000";
const sc_lv<1> maxPooling::ap_const_lv1_1 = "1";
const sc_lv<12> maxPooling::ap_const_lv12_0 = "000000000000";
const sc_lv<5> maxPooling::ap_const_lv5_0 = "00000";
const sc_lv<13> maxPooling::ap_const_lv13_0 = "0000000000000";
const sc_lv<2> maxPooling::ap_const_lv2_0 = "00";
const sc_lv<32> maxPooling::ap_const_lv32_9 = "1001";
const sc_lv<64> maxPooling::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<16> maxPooling::ap_const_lv16_0 = "0000000000000000";
const sc_lv<12> maxPooling::ap_const_lv12_1B = "11011";
const sc_lv<7> maxPooling::ap_const_lv7_60 = "1100000";
const sc_lv<7> maxPooling::ap_const_lv7_1 = "1";
const sc_lv<5> maxPooling::ap_const_lv5_1B = "11011";
const sc_lv<5> maxPooling::ap_const_lv5_1 = "1";
const sc_lv<32> maxPooling::ap_const_lv32_3F = "111111";
const sc_lv<13> maxPooling::ap_const_lv13_37 = "110111";
const sc_lv<2> maxPooling::ap_const_lv2_3 = "11";
const sc_lv<2> maxPooling::ap_const_lv2_1 = "1";
const bool maxPooling::ap_const_boolean_1 = true;

maxPooling::maxPooling(sc_module_name name) : sc_module(name), mVcdFile(0) {
    pool_values_V_U = new maxPooling_pool_vbkb("pool_values_V_U");
    pool_values_V_U->clk(ap_clk);
    pool_values_V_U->reset(ap_rst);
    pool_values_V_U->address0(pool_values_V_address0);
    pool_values_V_U->ce0(pool_values_V_ce0);
    pool_values_V_U->we0(pool_values_V_we0);
    pool_values_V_U->d0(input_V_q0);
    pool_values_V_U->q0(pool_values_V_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( exitcond2_fu_446_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( exitcond2_fu_446_p2 );

    SC_METHOD(thread_c_1_fu_337_p2);
    sensitive << ( c_reg_133 );

    SC_METHOD(thread_c_2_fu_452_p2);
    sensitive << ( c4_reg_178 );

    SC_METHOD(thread_exitcond1_fu_331_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( c_reg_133 );

    SC_METHOD(thread_exitcond2_fu_446_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( c4_reg_178 );

    SC_METHOD(thread_exitcond3_fu_343_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_reg_156 );

    SC_METHOD(thread_exitcond3_i_fu_665_p2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( i_i_reg_279 );

    SC_METHOD(thread_exitcond4_fu_458_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( i5_reg_213 );

    SC_METHOD(thread_exitcond5_fu_395_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( j_reg_167 );

    SC_METHOD(thread_exitcond6_fu_518_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( j6_reg_224 );

    SC_METHOD(thread_exitcond7_fu_542_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( pi_reg_236 );

    SC_METHOD(thread_exitcond_fu_621_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( pj_reg_247 );

    SC_METHOD(thread_exitcond_i_fu_726_p2);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( j_i_reg_314 );

    SC_METHOD(thread_i_1_fu_349_p2);
    sensitive << ( i_reg_156 );

    SC_METHOD(thread_i_2_fu_464_p2);
    sensitive << ( i5_reg_213 );

    SC_METHOD(thread_i_3_fu_671_p2);
    sensitive << ( i_i_reg_279 );

    SC_METHOD(thread_input_V_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_39_cast_fu_656_p1 );

    SC_METHOD(thread_input_V_ce0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_j_1_fu_401_p2);
    sensitive << ( j_reg_167 );

    SC_METHOD(thread_j_2_fu_524_p2);
    sensitive << ( j6_reg_224 );

    SC_METHOD(thread_j_3_fu_732_p2);
    sensitive << ( j_i_reg_314 );

    SC_METHOD(thread_max_value_V_1_agg_re_1_fu_766_p3);
    sensitive << ( pool_values_V_q0 );
    sensitive << ( agg_result_V_load_i_reg_302 );
    sensitive << ( tmp_13_i_fu_752_p2 );

    SC_METHOD(thread_max_value_V_1_agg_re_fu_758_p3);
    sensitive << ( pool_values_V_q0 );
    sensitive << ( agg_result_V_1_i_reg_290 );
    sensitive << ( tmp_13_i_fu_752_p2 );

    SC_METHOD(thread_next_mul1_fu_434_p2);
    sensitive << ( phi_mul1_reg_201 );

    SC_METHOD(thread_next_mul9_fu_440_p2);
    sensitive << ( phi_mul8_reg_189 );

    SC_METHOD(thread_next_mul_fu_325_p2);
    sensitive << ( phi_mul_reg_144 );

    SC_METHOD(thread_output_V_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_14_fu_425_p3 );
    sensitive << ( tmp_23_fu_717_p3 );

    SC_METHOD(thread_output_V_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_output_V_d0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( max_value_V_1_reg_258 );

    SC_METHOD(thread_output_V_we0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( exitcond3_i_fu_665_p2 );
    sensitive << ( exitcond5_fu_395_p2 );

    SC_METHOD(thread_p_shl1_fu_385_p1);
    sensitive << ( tmp_2_fu_377_p3 );

    SC_METHOD(thread_p_shl2_fu_496_p1);
    sensitive << ( tmp_6_fu_488_p3 );

    SC_METHOD(thread_p_shl3_fu_508_p1);
    sensitive << ( tmp_8_fu_500_p3 );

    SC_METHOD(thread_p_shl4_cast_fu_591_p3);
    sensitive << ( tmp_17_fu_585_p2 );

    SC_METHOD(thread_p_shl5_cast_fu_607_p1);
    sensitive << ( tmp_18_fu_599_p3 );

    SC_METHOD(thread_p_shl6_cast_fu_566_p1);
    sensitive << ( tmp_15_fu_558_p3 );

    SC_METHOD(thread_p_shl7_cast_fu_689_p1);
    sensitive << ( tmp_24_fu_681_p3 );

    SC_METHOD(thread_p_shl_fu_373_p1);
    sensitive << ( tmp_fu_365_p3 );

    SC_METHOD(thread_pi_1_fu_548_p2);
    sensitive << ( pi_reg_236 );

    SC_METHOD(thread_pi_cast6_fu_538_p1);
    sensitive << ( pi_reg_236 );

    SC_METHOD(thread_pj_1_fu_627_p2);
    sensitive << ( pj_reg_247 );

    SC_METHOD(thread_pj_cast4_fu_617_p1);
    sensitive << ( pj_reg_247 );

    SC_METHOD(thread_pool_values_V_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_38_cast_fu_661_p1 );
    sensitive << ( tmp_40_cast_fu_747_p1 );

    SC_METHOD(thread_pool_values_V_ce0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_pool_values_V_we0);
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_tmp_10_cast_fu_633_p1);
    sensitive << ( pj_reg_247 );

    SC_METHOD(thread_tmp_10_fu_407_p1);
    sensitive << ( tmp_3_reg_800 );

    SC_METHOD(thread_tmp_11_fu_642_p2);
    sensitive << ( tmp_s_reg_859 );
    sensitive << ( pj_cast4_fu_617_p1 );

    SC_METHOD(thread_tmp_12_cast_fu_647_p1);
    sensitive << ( tmp_11_fu_642_p2 );

    SC_METHOD(thread_tmp_12_fu_410_p2);
    sensitive << ( j_reg_167 );
    sensitive << ( tmp_10_fu_407_p1 );

    SC_METHOD(thread_tmp_13_fu_416_p4);
    sensitive << ( tmp_3_reg_800 );

    SC_METHOD(thread_tmp_13_i_fu_752_p2);
    sensitive << ( pool_values_V_q0 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( agg_result_V_load_i_reg_302 );

    SC_METHOD(thread_tmp_14_fu_425_p3);
    sensitive << ( tmp_13_fu_416_p4 );
    sensitive << ( tmp_12_fu_410_p2 );

    SC_METHOD(thread_tmp_15_fu_558_p3);
    sensitive << ( pi_reg_236 );

    SC_METHOD(thread_tmp_16_fu_570_p2);
    sensitive << ( p_shl6_cast_fu_566_p1 );
    sensitive << ( tmp_4_cast_fu_554_p1 );

    SC_METHOD(thread_tmp_17_fu_585_p2);
    sensitive << ( phi_mul8_reg_189 );
    sensitive << ( tmp_9_cast_fu_581_p1 );

    SC_METHOD(thread_tmp_18_fu_599_p3);
    sensitive << ( tmp_17_fu_585_p2 );

    SC_METHOD(thread_tmp_19_fu_611_p2);
    sensitive << ( p_shl4_cast_fu_591_p3 );
    sensitive << ( p_shl5_cast_fu_607_p1 );

    SC_METHOD(thread_tmp_1_fu_359_p2);
    sensitive << ( phi_mul_reg_144 );
    sensitive << ( tmp_3_cast_fu_355_p1 );

    SC_METHOD(thread_tmp_20_fu_699_p1);
    sensitive << ( tmp_9_reg_845 );

    SC_METHOD(thread_tmp_21_fu_702_p2);
    sensitive << ( j6_reg_224 );
    sensitive << ( tmp_20_fu_699_p1 );

    SC_METHOD(thread_tmp_22_fu_708_p4);
    sensitive << ( tmp_9_reg_845 );

    SC_METHOD(thread_tmp_23_fu_717_p3);
    sensitive << ( tmp_22_fu_708_p4 );
    sensitive << ( tmp_21_fu_702_p2 );

    SC_METHOD(thread_tmp_24_fu_681_p3);
    sensitive << ( i_i_reg_279 );

    SC_METHOD(thread_tmp_25_fu_693_p2);
    sensitive << ( p_shl7_cast_fu_689_p1 );
    sensitive << ( tmp_i_cast_fu_677_p1 );

    SC_METHOD(thread_tmp_26_fu_637_p2);
    sensitive << ( tmp_16_reg_872 );
    sensitive << ( tmp_10_cast_fu_633_p1 );

    SC_METHOD(thread_tmp_27_fu_651_p2);
    sensitive << ( tmp_19_reg_877 );
    sensitive << ( tmp_12_cast_fu_647_p1 );

    SC_METHOD(thread_tmp_28_fu_742_p2);
    sensitive << ( tmp_25_reg_914 );
    sensitive << ( tmp_i_cast_14_fu_738_p1 );

    SC_METHOD(thread_tmp_2_fu_377_p3);
    sensitive << ( tmp_1_fu_359_p2 );

    SC_METHOD(thread_tmp_38_cast_fu_661_p1);
    sensitive << ( tmp_26_reg_890 );

    SC_METHOD(thread_tmp_39_cast_fu_656_p1);
    sensitive << ( tmp_27_fu_651_p2 );

    SC_METHOD(thread_tmp_3_cast_fu_355_p1);
    sensitive << ( i_reg_156 );

    SC_METHOD(thread_tmp_3_fu_389_p2);
    sensitive << ( p_shl_fu_373_p1 );
    sensitive << ( p_shl1_fu_385_p1 );

    SC_METHOD(thread_tmp_40_cast_fu_747_p1);
    sensitive << ( tmp_28_fu_742_p2 );

    SC_METHOD(thread_tmp_4_cast_fu_554_p1);
    sensitive << ( pi_reg_236 );

    SC_METHOD(thread_tmp_4_fu_482_p2);
    sensitive << ( phi_mul1_reg_201 );
    sensitive << ( tmp_6_cast_fu_478_p1 );

    SC_METHOD(thread_tmp_5_fu_470_p3);
    sensitive << ( i5_reg_213 );

    SC_METHOD(thread_tmp_6_cast_fu_478_p1);
    sensitive << ( i5_reg_213 );

    SC_METHOD(thread_tmp_6_fu_488_p3);
    sensitive << ( tmp_4_fu_482_p2 );

    SC_METHOD(thread_tmp_7_fu_576_p2);
    sensitive << ( tmp_5_reg_840 );
    sensitive << ( pi_cast6_fu_538_p1 );

    SC_METHOD(thread_tmp_8_fu_500_p3);
    sensitive << ( tmp_4_fu_482_p2 );

    SC_METHOD(thread_tmp_9_cast_fu_581_p1);
    sensitive << ( tmp_7_fu_576_p2 );

    SC_METHOD(thread_tmp_9_fu_512_p2);
    sensitive << ( p_shl2_fu_496_p1 );
    sensitive << ( p_shl3_fu_508_p1 );

    SC_METHOD(thread_tmp_fu_365_p3);
    sensitive << ( tmp_1_fu_359_p2 );

    SC_METHOD(thread_tmp_i_cast_14_fu_738_p1);
    sensitive << ( j_i_reg_314 );

    SC_METHOD(thread_tmp_i_cast_fu_677_p1);
    sensitive << ( i_i_reg_279 );

    SC_METHOD(thread_tmp_s_fu_530_p3);
    sensitive << ( j6_reg_224 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond3_fu_343_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( exitcond4_fu_458_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond6_fu_518_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond7_fu_542_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( exitcond_fu_621_p2 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( exitcond3_i_fu_665_p2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( exitcond_i_fu_726_p2 );
    sensitive << ( exitcond5_fu_395_p2 );
    sensitive << ( exitcond1_fu_331_p2 );
    sensitive << ( exitcond2_fu_446_p2 );

    ap_CS_fsm = "00000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "maxPooling_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_V_address0, "(port)input_V_address0");
    sc_trace(mVcdFile, input_V_ce0, "(port)input_V_ce0");
    sc_trace(mVcdFile, input_V_q0, "(port)input_V_q0");
    sc_trace(mVcdFile, output_V_address0, "(port)output_V_address0");
    sc_trace(mVcdFile, output_V_ce0, "(port)output_V_ce0");
    sc_trace(mVcdFile, output_V_we0, "(port)output_V_we0");
    sc_trace(mVcdFile, output_V_d0, "(port)output_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, next_mul_fu_325_p2, "next_mul_fu_325_p2");
    sc_trace(mVcdFile, next_mul_reg_779, "next_mul_reg_779");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, c_1_fu_337_p2, "c_1_fu_337_p2");
    sc_trace(mVcdFile, c_1_reg_787, "c_1_reg_787");
    sc_trace(mVcdFile, i_1_fu_349_p2, "i_1_fu_349_p2");
    sc_trace(mVcdFile, i_1_reg_795, "i_1_reg_795");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_3_fu_389_p2, "tmp_3_fu_389_p2");
    sc_trace(mVcdFile, tmp_3_reg_800, "tmp_3_reg_800");
    sc_trace(mVcdFile, exitcond3_fu_343_p2, "exitcond3_fu_343_p2");
    sc_trace(mVcdFile, j_1_fu_401_p2, "j_1_fu_401_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, next_mul1_fu_434_p2, "next_mul1_fu_434_p2");
    sc_trace(mVcdFile, next_mul1_reg_814, "next_mul1_reg_814");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, next_mul9_fu_440_p2, "next_mul9_fu_440_p2");
    sc_trace(mVcdFile, next_mul9_reg_819, "next_mul9_reg_819");
    sc_trace(mVcdFile, c_2_fu_452_p2, "c_2_fu_452_p2");
    sc_trace(mVcdFile, c_2_reg_827, "c_2_reg_827");
    sc_trace(mVcdFile, i_2_fu_464_p2, "i_2_fu_464_p2");
    sc_trace(mVcdFile, i_2_reg_835, "i_2_reg_835");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_5_fu_470_p3, "tmp_5_fu_470_p3");
    sc_trace(mVcdFile, tmp_5_reg_840, "tmp_5_reg_840");
    sc_trace(mVcdFile, exitcond4_fu_458_p2, "exitcond4_fu_458_p2");
    sc_trace(mVcdFile, tmp_9_fu_512_p2, "tmp_9_fu_512_p2");
    sc_trace(mVcdFile, tmp_9_reg_845, "tmp_9_reg_845");
    sc_trace(mVcdFile, j_2_fu_524_p2, "j_2_fu_524_p2");
    sc_trace(mVcdFile, j_2_reg_854, "j_2_reg_854");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_s_fu_530_p3, "tmp_s_fu_530_p3");
    sc_trace(mVcdFile, tmp_s_reg_859, "tmp_s_reg_859");
    sc_trace(mVcdFile, exitcond6_fu_518_p2, "exitcond6_fu_518_p2");
    sc_trace(mVcdFile, pi_1_fu_548_p2, "pi_1_fu_548_p2");
    sc_trace(mVcdFile, pi_1_reg_867, "pi_1_reg_867");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, tmp_16_fu_570_p2, "tmp_16_fu_570_p2");
    sc_trace(mVcdFile, tmp_16_reg_872, "tmp_16_reg_872");
    sc_trace(mVcdFile, exitcond7_fu_542_p2, "exitcond7_fu_542_p2");
    sc_trace(mVcdFile, tmp_19_fu_611_p2, "tmp_19_fu_611_p2");
    sc_trace(mVcdFile, tmp_19_reg_877, "tmp_19_reg_877");
    sc_trace(mVcdFile, pj_1_fu_627_p2, "pj_1_fu_627_p2");
    sc_trace(mVcdFile, pj_1_reg_885, "pj_1_reg_885");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, tmp_26_fu_637_p2, "tmp_26_fu_637_p2");
    sc_trace(mVcdFile, tmp_26_reg_890, "tmp_26_reg_890");
    sc_trace(mVcdFile, exitcond_fu_621_p2, "exitcond_fu_621_p2");
    sc_trace(mVcdFile, pool_values_V_q0, "pool_values_V_q0");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, i_3_fu_671_p2, "i_3_fu_671_p2");
    sc_trace(mVcdFile, i_3_reg_909, "i_3_reg_909");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, tmp_25_fu_693_p2, "tmp_25_fu_693_p2");
    sc_trace(mVcdFile, tmp_25_reg_914, "tmp_25_reg_914");
    sc_trace(mVcdFile, exitcond3_i_fu_665_p2, "exitcond3_i_fu_665_p2");
    sc_trace(mVcdFile, j_3_fu_732_p2, "j_3_fu_732_p2");
    sc_trace(mVcdFile, j_3_reg_922, "j_3_reg_922");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, exitcond_i_fu_726_p2, "exitcond_i_fu_726_p2");
    sc_trace(mVcdFile, max_value_V_1_agg_re_fu_758_p3, "max_value_V_1_agg_re_fu_758_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, max_value_V_1_agg_re_1_fu_766_p3, "max_value_V_1_agg_re_1_fu_766_p3");
    sc_trace(mVcdFile, pool_values_V_address0, "pool_values_V_address0");
    sc_trace(mVcdFile, pool_values_V_ce0, "pool_values_V_ce0");
    sc_trace(mVcdFile, pool_values_V_we0, "pool_values_V_we0");
    sc_trace(mVcdFile, c_reg_133, "c_reg_133");
    sc_trace(mVcdFile, phi_mul_reg_144, "phi_mul_reg_144");
    sc_trace(mVcdFile, i_reg_156, "i_reg_156");
    sc_trace(mVcdFile, exitcond5_fu_395_p2, "exitcond5_fu_395_p2");
    sc_trace(mVcdFile, exitcond1_fu_331_p2, "exitcond1_fu_331_p2");
    sc_trace(mVcdFile, j_reg_167, "j_reg_167");
    sc_trace(mVcdFile, c4_reg_178, "c4_reg_178");
    sc_trace(mVcdFile, phi_mul8_reg_189, "phi_mul8_reg_189");
    sc_trace(mVcdFile, phi_mul1_reg_201, "phi_mul1_reg_201");
    sc_trace(mVcdFile, i5_reg_213, "i5_reg_213");
    sc_trace(mVcdFile, exitcond2_fu_446_p2, "exitcond2_fu_446_p2");
    sc_trace(mVcdFile, j6_reg_224, "j6_reg_224");
    sc_trace(mVcdFile, pi_reg_236, "pi_reg_236");
    sc_trace(mVcdFile, pj_reg_247, "pj_reg_247");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, max_value_V_1_reg_258, "max_value_V_1_reg_258");
    sc_trace(mVcdFile, agg_result_V_load4_i_reg_269, "agg_result_V_load4_i_reg_269");
    sc_trace(mVcdFile, i_i_reg_279, "i_i_reg_279");
    sc_trace(mVcdFile, agg_result_V_1_i_reg_290, "agg_result_V_1_i_reg_290");
    sc_trace(mVcdFile, agg_result_V_load_i_reg_302, "agg_result_V_load_i_reg_302");
    sc_trace(mVcdFile, j_i_reg_314, "j_i_reg_314");
    sc_trace(mVcdFile, tmp_14_fu_425_p3, "tmp_14_fu_425_p3");
    sc_trace(mVcdFile, tmp_39_cast_fu_656_p1, "tmp_39_cast_fu_656_p1");
    sc_trace(mVcdFile, tmp_38_cast_fu_661_p1, "tmp_38_cast_fu_661_p1");
    sc_trace(mVcdFile, tmp_23_fu_717_p3, "tmp_23_fu_717_p3");
    sc_trace(mVcdFile, tmp_40_cast_fu_747_p1, "tmp_40_cast_fu_747_p1");
    sc_trace(mVcdFile, tmp_3_cast_fu_355_p1, "tmp_3_cast_fu_355_p1");
    sc_trace(mVcdFile, tmp_1_fu_359_p2, "tmp_1_fu_359_p2");
    sc_trace(mVcdFile, tmp_fu_365_p3, "tmp_fu_365_p3");
    sc_trace(mVcdFile, tmp_2_fu_377_p3, "tmp_2_fu_377_p3");
    sc_trace(mVcdFile, p_shl_fu_373_p1, "p_shl_fu_373_p1");
    sc_trace(mVcdFile, p_shl1_fu_385_p1, "p_shl1_fu_385_p1");
    sc_trace(mVcdFile, tmp_10_fu_407_p1, "tmp_10_fu_407_p1");
    sc_trace(mVcdFile, tmp_13_fu_416_p4, "tmp_13_fu_416_p4");
    sc_trace(mVcdFile, tmp_12_fu_410_p2, "tmp_12_fu_410_p2");
    sc_trace(mVcdFile, tmp_6_cast_fu_478_p1, "tmp_6_cast_fu_478_p1");
    sc_trace(mVcdFile, tmp_4_fu_482_p2, "tmp_4_fu_482_p2");
    sc_trace(mVcdFile, tmp_6_fu_488_p3, "tmp_6_fu_488_p3");
    sc_trace(mVcdFile, tmp_8_fu_500_p3, "tmp_8_fu_500_p3");
    sc_trace(mVcdFile, p_shl2_fu_496_p1, "p_shl2_fu_496_p1");
    sc_trace(mVcdFile, p_shl3_fu_508_p1, "p_shl3_fu_508_p1");
    sc_trace(mVcdFile, tmp_15_fu_558_p3, "tmp_15_fu_558_p3");
    sc_trace(mVcdFile, p_shl6_cast_fu_566_p1, "p_shl6_cast_fu_566_p1");
    sc_trace(mVcdFile, tmp_4_cast_fu_554_p1, "tmp_4_cast_fu_554_p1");
    sc_trace(mVcdFile, pi_cast6_fu_538_p1, "pi_cast6_fu_538_p1");
    sc_trace(mVcdFile, tmp_7_fu_576_p2, "tmp_7_fu_576_p2");
    sc_trace(mVcdFile, tmp_9_cast_fu_581_p1, "tmp_9_cast_fu_581_p1");
    sc_trace(mVcdFile, tmp_17_fu_585_p2, "tmp_17_fu_585_p2");
    sc_trace(mVcdFile, tmp_18_fu_599_p3, "tmp_18_fu_599_p3");
    sc_trace(mVcdFile, p_shl4_cast_fu_591_p3, "p_shl4_cast_fu_591_p3");
    sc_trace(mVcdFile, p_shl5_cast_fu_607_p1, "p_shl5_cast_fu_607_p1");
    sc_trace(mVcdFile, tmp_10_cast_fu_633_p1, "tmp_10_cast_fu_633_p1");
    sc_trace(mVcdFile, pj_cast4_fu_617_p1, "pj_cast4_fu_617_p1");
    sc_trace(mVcdFile, tmp_11_fu_642_p2, "tmp_11_fu_642_p2");
    sc_trace(mVcdFile, tmp_12_cast_fu_647_p1, "tmp_12_cast_fu_647_p1");
    sc_trace(mVcdFile, tmp_27_fu_651_p2, "tmp_27_fu_651_p2");
    sc_trace(mVcdFile, tmp_24_fu_681_p3, "tmp_24_fu_681_p3");
    sc_trace(mVcdFile, p_shl7_cast_fu_689_p1, "p_shl7_cast_fu_689_p1");
    sc_trace(mVcdFile, tmp_i_cast_fu_677_p1, "tmp_i_cast_fu_677_p1");
    sc_trace(mVcdFile, tmp_20_fu_699_p1, "tmp_20_fu_699_p1");
    sc_trace(mVcdFile, tmp_22_fu_708_p4, "tmp_22_fu_708_p4");
    sc_trace(mVcdFile, tmp_21_fu_702_p2, "tmp_21_fu_702_p2");
    sc_trace(mVcdFile, tmp_i_cast_14_fu_738_p1, "tmp_i_cast_14_fu_738_p1");
    sc_trace(mVcdFile, tmp_28_fu_742_p2, "tmp_28_fu_742_p2");
    sc_trace(mVcdFile, tmp_13_i_fu_752_p2, "tmp_13_i_fu_752_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

maxPooling::~maxPooling() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete pool_values_V_U;
}

void maxPooling::thread_ap_clk_no_reset_() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        agg_result_V_1_i_reg_290 = max_value_V_1_agg_re_fu_758_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_i_fu_665_p2.read()))) {
        agg_result_V_1_i_reg_290 = max_value_V_1_reg_258.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
         esl_seteq<1,1,1>(exitcond_i_fu_726_p2.read(), ap_const_lv1_1))) {
        agg_result_V_load4_i_reg_269 = agg_result_V_load_i_reg_302.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        agg_result_V_load4_i_reg_269 = pool_values_V_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        agg_result_V_load_i_reg_302 = max_value_V_1_agg_re_1_fu_766_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_i_fu_665_p2.read()))) {
        agg_result_V_load_i_reg_302 = agg_result_V_load4_i_reg_269.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_fu_331_p2.read()))) {
        c4_reg_178 = ap_const_lv7_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(exitcond4_fu_458_p2.read(), ap_const_lv1_1))) {
        c4_reg_178 = c_2_reg_827.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond3_fu_343_p2.read(), ap_const_lv1_1))) {
        c_reg_133 = c_1_reg_787.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        c_reg_133 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_446_p2.read()))) {
        i5_reg_213 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(exitcond6_fu_518_p2.read(), ap_const_lv1_1))) {
        i5_reg_213 = i_2_reg_835.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
         esl_seteq<1,1,1>(exitcond_i_fu_726_p2.read(), ap_const_lv1_1))) {
        i_i_reg_279 = i_3_reg_909.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        i_i_reg_279 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_331_p2.read()))) {
        i_reg_156 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, exitcond5_fu_395_p2.read()))) {
        i_reg_156 = i_1_reg_795.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_458_p2.read()))) {
        j6_reg_224 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
                esl_seteq<1,1,1>(exitcond3_i_fu_665_p2.read(), ap_const_lv1_1))) {
        j6_reg_224 = j_2_reg_854.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        j_i_reg_314 = j_3_reg_922.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_i_fu_665_p2.read()))) {
        j_i_reg_314 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond3_fu_343_p2.read(), ap_const_lv1_0))) {
        j_reg_167 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_395_p2.read()))) {
        j_reg_167 = j_1_fu_401_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
         esl_seteq<1,1,1>(exitcond_i_fu_726_p2.read(), ap_const_lv1_1))) {
        max_value_V_1_reg_258 = agg_result_V_1_i_reg_290.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        max_value_V_1_reg_258 = pool_values_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_fu_331_p2.read()))) {
        phi_mul1_reg_201 = ap_const_lv12_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(exitcond4_fu_458_p2.read(), ap_const_lv1_1))) {
        phi_mul1_reg_201 = next_mul1_reg_814.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_fu_331_p2.read()))) {
        phi_mul8_reg_189 = ap_const_lv13_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(exitcond4_fu_458_p2.read(), ap_const_lv1_1))) {
        phi_mul8_reg_189 = next_mul9_reg_819.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond3_fu_343_p2.read(), ap_const_lv1_1))) {
        phi_mul_reg_144 = next_mul_reg_779.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        phi_mul_reg_144 = ap_const_lv12_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_621_p2.read(), ap_const_lv1_1))) {
        pi_reg_236 = pi_1_reg_867.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_518_p2.read()))) {
        pi_reg_236 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_542_p2.read()))) {
        pj_reg_247 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        pj_reg_247 = pj_1_reg_885.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        c_1_reg_787 = c_1_fu_337_p2.read();
        next_mul_reg_779 = next_mul_fu_325_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        c_2_reg_827 = c_2_fu_452_p2.read();
        next_mul1_reg_814 = next_mul1_fu_434_p2.read();
        next_mul9_reg_819 = next_mul9_fu_440_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_1_reg_795 = i_1_fu_349_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_2_reg_835 = i_2_fu_464_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        i_3_reg_909 = i_3_fu_671_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        j_2_reg_854 = j_2_fu_524_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        j_3_reg_922 = j_3_fu_732_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        pi_1_reg_867 = pi_1_fu_548_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        pj_1_reg_885 = pj_1_fu_627_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_542_p2.read()))) {
        tmp_16_reg_872 = tmp_16_fu_570_p2.read();
        tmp_19_reg_877 = tmp_19_fu_611_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_i_fu_665_p2.read()))) {
        tmp_25_reg_914 = tmp_25_fu_693_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_621_p2.read()))) {
        tmp_26_reg_890 = tmp_26_fu_637_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond3_fu_343_p2.read(), ap_const_lv1_0))) {
        tmp_3_reg_800 = tmp_3_fu_389_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_458_p2.read()))) {
        tmp_5_reg_840 = tmp_5_fu_470_p3.read();
        tmp_9_reg_845 = tmp_9_fu_512_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_518_p2.read()))) {
        tmp_s_reg_859 = tmp_s_fu_530_p3.read();
    }
}

void maxPooling::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void maxPooling::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void maxPooling::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void maxPooling::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void maxPooling::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void maxPooling::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void maxPooling::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void maxPooling::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void maxPooling::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void maxPooling::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void maxPooling::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void maxPooling::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void maxPooling::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void maxPooling::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void maxPooling::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_446_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void maxPooling::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void maxPooling::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_446_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void maxPooling::thread_c_1_fu_337_p2() {
    c_1_fu_337_p2 = (!c_reg_133.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(c_reg_133.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void maxPooling::thread_c_2_fu_452_p2() {
    c_2_fu_452_p2 = (!c4_reg_178.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(c4_reg_178.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void maxPooling::thread_exitcond1_fu_331_p2() {
    exitcond1_fu_331_p2 = (!c_reg_133.read().is_01() || !ap_const_lv7_60.is_01())? sc_lv<1>(): sc_lv<1>(c_reg_133.read() == ap_const_lv7_60);
}

void maxPooling::thread_exitcond2_fu_446_p2() {
    exitcond2_fu_446_p2 = (!c4_reg_178.read().is_01() || !ap_const_lv7_60.is_01())? sc_lv<1>(): sc_lv<1>(c4_reg_178.read() == ap_const_lv7_60);
}

void maxPooling::thread_exitcond3_fu_343_p2() {
    exitcond3_fu_343_p2 = (!i_reg_156.read().is_01() || !ap_const_lv5_1B.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_156.read() == ap_const_lv5_1B);
}

void maxPooling::thread_exitcond3_i_fu_665_p2() {
    exitcond3_i_fu_665_p2 = (!i_i_reg_279.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i_i_reg_279.read() == ap_const_lv2_3);
}

void maxPooling::thread_exitcond4_fu_458_p2() {
    exitcond4_fu_458_p2 = (!i5_reg_213.read().is_01() || !ap_const_lv5_1B.is_01())? sc_lv<1>(): sc_lv<1>(i5_reg_213.read() == ap_const_lv5_1B);
}

void maxPooling::thread_exitcond5_fu_395_p2() {
    exitcond5_fu_395_p2 = (!j_reg_167.read().is_01() || !ap_const_lv5_1B.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_167.read() == ap_const_lv5_1B);
}

void maxPooling::thread_exitcond6_fu_518_p2() {
    exitcond6_fu_518_p2 = (!j6_reg_224.read().is_01() || !ap_const_lv5_1B.is_01())? sc_lv<1>(): sc_lv<1>(j6_reg_224.read() == ap_const_lv5_1B);
}

void maxPooling::thread_exitcond7_fu_542_p2() {
    exitcond7_fu_542_p2 = (!pi_reg_236.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(pi_reg_236.read() == ap_const_lv2_3);
}

void maxPooling::thread_exitcond_fu_621_p2() {
    exitcond_fu_621_p2 = (!pj_reg_247.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(pj_reg_247.read() == ap_const_lv2_3);
}

void maxPooling::thread_exitcond_i_fu_726_p2() {
    exitcond_i_fu_726_p2 = (!j_i_reg_314.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(j_i_reg_314.read() == ap_const_lv2_3);
}

void maxPooling::thread_i_1_fu_349_p2() {
    i_1_fu_349_p2 = (!i_reg_156.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_reg_156.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void maxPooling::thread_i_2_fu_464_p2() {
    i_2_fu_464_p2 = (!i5_reg_213.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i5_reg_213.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void maxPooling::thread_i_3_fu_671_p2() {
    i_3_fu_671_p2 = (!i_i_reg_279.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i_i_reg_279.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void maxPooling::thread_input_V_address0() {
    input_V_address0 =  (sc_lv<19>) (tmp_39_cast_fu_656_p1.read());
}

void maxPooling::thread_input_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        input_V_ce0 = ap_const_logic_1;
    } else {
        input_V_ce0 = ap_const_logic_0;
    }
}

void maxPooling::thread_j_1_fu_401_p2() {
    j_1_fu_401_p2 = (!j_reg_167.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(j_reg_167.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void maxPooling::thread_j_2_fu_524_p2() {
    j_2_fu_524_p2 = (!j6_reg_224.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(j6_reg_224.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void maxPooling::thread_j_3_fu_732_p2() {
    j_3_fu_732_p2 = (!j_i_reg_314.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(j_i_reg_314.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void maxPooling::thread_max_value_V_1_agg_re_1_fu_766_p3() {
    max_value_V_1_agg_re_1_fu_766_p3 = (!tmp_13_i_fu_752_p2.read()[0].is_01())? sc_lv<16>(): ((tmp_13_i_fu_752_p2.read()[0].to_bool())? pool_values_V_q0.read(): agg_result_V_load_i_reg_302.read());
}

void maxPooling::thread_max_value_V_1_agg_re_fu_758_p3() {
    max_value_V_1_agg_re_fu_758_p3 = (!tmp_13_i_fu_752_p2.read()[0].is_01())? sc_lv<16>(): ((tmp_13_i_fu_752_p2.read()[0].to_bool())? pool_values_V_q0.read(): agg_result_V_1_i_reg_290.read());
}

void maxPooling::thread_next_mul1_fu_434_p2() {
    next_mul1_fu_434_p2 = (!phi_mul1_reg_201.read().is_01() || !ap_const_lv12_1B.is_01())? sc_lv<12>(): (sc_biguint<12>(phi_mul1_reg_201.read()) + sc_biguint<12>(ap_const_lv12_1B));
}

void maxPooling::thread_next_mul9_fu_440_p2() {
    next_mul9_fu_440_p2 = (!phi_mul8_reg_189.read().is_01() || !ap_const_lv13_37.is_01())? sc_lv<13>(): (sc_biguint<13>(phi_mul8_reg_189.read()) + sc_biguint<13>(ap_const_lv13_37));
}

void maxPooling::thread_next_mul_fu_325_p2() {
    next_mul_fu_325_p2 = (!phi_mul_reg_144.read().is_01() || !ap_const_lv12_1B.is_01())? sc_lv<12>(): (sc_biguint<12>(phi_mul_reg_144.read()) + sc_biguint<12>(ap_const_lv12_1B));
}

void maxPooling::thread_output_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        output_V_address0 =  (sc_lv<17>) (tmp_23_fu_717_p3.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        output_V_address0 =  (sc_lv<17>) (tmp_14_fu_425_p3.read());
    } else {
        output_V_address0 = "XXXXXXXXXXXXXXXXX";
    }
}

void maxPooling::thread_output_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        output_V_ce0 = ap_const_logic_1;
    } else {
        output_V_ce0 = ap_const_logic_0;
    }
}

void maxPooling::thread_output_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        output_V_d0 = max_value_V_1_reg_258.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        output_V_d0 = ap_const_lv16_0;
    } else {
        output_V_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void maxPooling::thread_output_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_395_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
          esl_seteq<1,1,1>(exitcond3_i_fu_665_p2.read(), ap_const_lv1_1)))) {
        output_V_we0 = ap_const_logic_1;
    } else {
        output_V_we0 = ap_const_logic_0;
    }
}

void maxPooling::thread_p_shl1_fu_385_p1() {
    p_shl1_fu_385_p1 = esl_zext<64,17>(tmp_2_fu_377_p3.read());
}

void maxPooling::thread_p_shl2_fu_496_p1() {
    p_shl2_fu_496_p1 = esl_zext<64,19>(tmp_6_fu_488_p3.read());
}

void maxPooling::thread_p_shl3_fu_508_p1() {
    p_shl3_fu_508_p1 = esl_zext<64,17>(tmp_8_fu_500_p3.read());
}

void maxPooling::thread_p_shl4_cast_fu_591_p3() {
    p_shl4_cast_fu_591_p3 = esl_concat<13,7>(tmp_17_fu_585_p2.read(), ap_const_lv7_0);
}

void maxPooling::thread_p_shl5_cast_fu_607_p1() {
    p_shl5_cast_fu_607_p1 = esl_zext<20,18>(tmp_18_fu_599_p3.read());
}

void maxPooling::thread_p_shl6_cast_fu_566_p1() {
    p_shl6_cast_fu_566_p1 = esl_zext<5,4>(tmp_15_fu_558_p3.read());
}

void maxPooling::thread_p_shl7_cast_fu_689_p1() {
    p_shl7_cast_fu_689_p1 = esl_zext<5,4>(tmp_24_fu_681_p3.read());
}

void maxPooling::thread_p_shl_fu_373_p1() {
    p_shl_fu_373_p1 = esl_zext<64,19>(tmp_fu_365_p3.read());
}

void maxPooling::thread_pi_1_fu_548_p2() {
    pi_1_fu_548_p2 = (!pi_reg_236.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(pi_reg_236.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void maxPooling::thread_pi_cast6_fu_538_p1() {
    pi_cast6_fu_538_p1 = esl_zext<6,2>(pi_reg_236.read());
}

void maxPooling::thread_pj_1_fu_627_p2() {
    pj_1_fu_627_p2 = (!pj_reg_247.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(pj_reg_247.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void maxPooling::thread_pj_cast4_fu_617_p1() {
    pj_cast4_fu_617_p1 = esl_zext<6,2>(pj_reg_247.read());
}

void maxPooling::thread_pool_values_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        pool_values_V_address0 =  (sc_lv<4>) (tmp_40_cast_fu_747_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        pool_values_V_address0 =  (sc_lv<4>) (tmp_38_cast_fu_661_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        pool_values_V_address0 =  (sc_lv<4>) (ap_const_lv64_0);
    } else {
        pool_values_V_address0 =  (sc_lv<4>) ("XXXX");
    }
}

void maxPooling::thread_pool_values_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        pool_values_V_ce0 = ap_const_logic_1;
    } else {
        pool_values_V_ce0 = ap_const_logic_0;
    }
}

void maxPooling::thread_pool_values_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        pool_values_V_we0 = ap_const_logic_1;
    } else {
        pool_values_V_we0 = ap_const_logic_0;
    }
}

void maxPooling::thread_tmp_10_cast_fu_633_p1() {
    tmp_10_cast_fu_633_p1 = esl_zext<5,2>(pj_reg_247.read());
}

void maxPooling::thread_tmp_10_fu_407_p1() {
    tmp_10_fu_407_p1 = tmp_3_reg_800.read().range(5-1, 0);
}

void maxPooling::thread_tmp_11_fu_642_p2() {
    tmp_11_fu_642_p2 = (!pj_cast4_fu_617_p1.read().is_01() || !tmp_s_reg_859.read().is_01())? sc_lv<6>(): (sc_biguint<6>(pj_cast4_fu_617_p1.read()) + sc_biguint<6>(tmp_s_reg_859.read()));
}

void maxPooling::thread_tmp_12_cast_fu_647_p1() {
    tmp_12_cast_fu_647_p1 = esl_zext<20,6>(tmp_11_fu_642_p2.read());
}

void maxPooling::thread_tmp_12_fu_410_p2() {
    tmp_12_fu_410_p2 = (tmp_10_fu_407_p1.read() | j_reg_167.read());
}

void maxPooling::thread_tmp_13_fu_416_p4() {
    tmp_13_fu_416_p4 = tmp_3_reg_800.read().range(63, 5);
}

void maxPooling::thread_tmp_13_i_fu_752_p2() {
    tmp_13_i_fu_752_p2 = (!pool_values_V_q0.read().is_01() || !agg_result_V_load_i_reg_302.read().is_01())? sc_lv<1>(): (sc_bigint<16>(pool_values_V_q0.read()) > sc_bigint<16>(agg_result_V_load_i_reg_302.read()));
}

void maxPooling::thread_tmp_14_fu_425_p3() {
    tmp_14_fu_425_p3 = esl_concat<59,5>(tmp_13_fu_416_p4.read(), tmp_12_fu_410_p2.read());
}

void maxPooling::thread_tmp_15_fu_558_p3() {
    tmp_15_fu_558_p3 = esl_concat<2,2>(pi_reg_236.read(), ap_const_lv2_0);
}

void maxPooling::thread_tmp_16_fu_570_p2() {
    tmp_16_fu_570_p2 = (!p_shl6_cast_fu_566_p1.read().is_01() || !tmp_4_cast_fu_554_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(p_shl6_cast_fu_566_p1.read()) - sc_biguint<5>(tmp_4_cast_fu_554_p1.read()));
}

void maxPooling::thread_tmp_17_fu_585_p2() {
    tmp_17_fu_585_p2 = (!tmp_9_cast_fu_581_p1.read().is_01() || !phi_mul8_reg_189.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp_9_cast_fu_581_p1.read()) + sc_biguint<13>(phi_mul8_reg_189.read()));
}

void maxPooling::thread_tmp_18_fu_599_p3() {
    tmp_18_fu_599_p3 = esl_concat<13,5>(tmp_17_fu_585_p2.read(), ap_const_lv5_0);
}

void maxPooling::thread_tmp_19_fu_611_p2() {
    tmp_19_fu_611_p2 = (!p_shl4_cast_fu_591_p3.read().is_01() || !p_shl5_cast_fu_607_p1.read().is_01())? sc_lv<20>(): (sc_biguint<20>(p_shl4_cast_fu_591_p3.read()) - sc_biguint<20>(p_shl5_cast_fu_607_p1.read()));
}

void maxPooling::thread_tmp_1_fu_359_p2() {
    tmp_1_fu_359_p2 = (!phi_mul_reg_144.read().is_01() || !tmp_3_cast_fu_355_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(phi_mul_reg_144.read()) + sc_biguint<12>(tmp_3_cast_fu_355_p1.read()));
}

void maxPooling::thread_tmp_20_fu_699_p1() {
    tmp_20_fu_699_p1 = tmp_9_reg_845.read().range(5-1, 0);
}

void maxPooling::thread_tmp_21_fu_702_p2() {
    tmp_21_fu_702_p2 = (tmp_20_fu_699_p1.read() | j6_reg_224.read());
}

void maxPooling::thread_tmp_22_fu_708_p4() {
    tmp_22_fu_708_p4 = tmp_9_reg_845.read().range(63, 5);
}

void maxPooling::thread_tmp_23_fu_717_p3() {
    tmp_23_fu_717_p3 = esl_concat<59,5>(tmp_22_fu_708_p4.read(), tmp_21_fu_702_p2.read());
}

void maxPooling::thread_tmp_24_fu_681_p3() {
    tmp_24_fu_681_p3 = esl_concat<2,2>(i_i_reg_279.read(), ap_const_lv2_0);
}

void maxPooling::thread_tmp_25_fu_693_p2() {
    tmp_25_fu_693_p2 = (!p_shl7_cast_fu_689_p1.read().is_01() || !tmp_i_cast_fu_677_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(p_shl7_cast_fu_689_p1.read()) - sc_biguint<5>(tmp_i_cast_fu_677_p1.read()));
}

void maxPooling::thread_tmp_26_fu_637_p2() {
    tmp_26_fu_637_p2 = (!tmp_16_reg_872.read().is_01() || !tmp_10_cast_fu_633_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_16_reg_872.read()) + sc_biguint<5>(tmp_10_cast_fu_633_p1.read()));
}

void maxPooling::thread_tmp_27_fu_651_p2() {
    tmp_27_fu_651_p2 = (!tmp_19_reg_877.read().is_01() || !tmp_12_cast_fu_647_p1.read().is_01())? sc_lv<20>(): (sc_biguint<20>(tmp_19_reg_877.read()) + sc_biguint<20>(tmp_12_cast_fu_647_p1.read()));
}

void maxPooling::thread_tmp_28_fu_742_p2() {
    tmp_28_fu_742_p2 = (!tmp_25_reg_914.read().is_01() || !tmp_i_cast_14_fu_738_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_25_reg_914.read()) + sc_biguint<5>(tmp_i_cast_14_fu_738_p1.read()));
}

void maxPooling::thread_tmp_2_fu_377_p3() {
    tmp_2_fu_377_p3 = esl_concat<12,5>(tmp_1_fu_359_p2.read(), ap_const_lv5_0);
}

void maxPooling::thread_tmp_38_cast_fu_661_p1() {
    tmp_38_cast_fu_661_p1 = esl_sext<64,5>(tmp_26_reg_890.read());
}

void maxPooling::thread_tmp_39_cast_fu_656_p1() {
    tmp_39_cast_fu_656_p1 = esl_zext<64,20>(tmp_27_fu_651_p2.read());
}

void maxPooling::thread_tmp_3_cast_fu_355_p1() {
    tmp_3_cast_fu_355_p1 = esl_zext<12,5>(i_reg_156.read());
}

void maxPooling::thread_tmp_3_fu_389_p2() {
    tmp_3_fu_389_p2 = (!p_shl_fu_373_p1.read().is_01() || !p_shl1_fu_385_p1.read().is_01())? sc_lv<64>(): (sc_biguint<64>(p_shl_fu_373_p1.read()) - sc_biguint<64>(p_shl1_fu_385_p1.read()));
}

void maxPooling::thread_tmp_40_cast_fu_747_p1() {
    tmp_40_cast_fu_747_p1 = esl_sext<64,5>(tmp_28_fu_742_p2.read());
}

void maxPooling::thread_tmp_4_cast_fu_554_p1() {
    tmp_4_cast_fu_554_p1 = esl_zext<5,2>(pi_reg_236.read());
}

void maxPooling::thread_tmp_4_fu_482_p2() {
    tmp_4_fu_482_p2 = (!tmp_6_cast_fu_478_p1.read().is_01() || !phi_mul1_reg_201.read().is_01())? sc_lv<12>(): (sc_biguint<12>(tmp_6_cast_fu_478_p1.read()) + sc_biguint<12>(phi_mul1_reg_201.read()));
}

void maxPooling::thread_tmp_5_fu_470_p3() {
    tmp_5_fu_470_p3 = esl_concat<5,1>(i5_reg_213.read(), ap_const_lv1_0);
}

void maxPooling::thread_tmp_6_cast_fu_478_p1() {
    tmp_6_cast_fu_478_p1 = esl_zext<12,5>(i5_reg_213.read());
}

void maxPooling::thread_tmp_6_fu_488_p3() {
    tmp_6_fu_488_p3 = esl_concat<12,7>(tmp_4_fu_482_p2.read(), ap_const_lv7_0);
}

void maxPooling::thread_tmp_7_fu_576_p2() {
    tmp_7_fu_576_p2 = (!tmp_5_reg_840.read().is_01() || !pi_cast6_fu_538_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_5_reg_840.read()) + sc_biguint<6>(pi_cast6_fu_538_p1.read()));
}

void maxPooling::thread_tmp_8_fu_500_p3() {
    tmp_8_fu_500_p3 = esl_concat<12,5>(tmp_4_fu_482_p2.read(), ap_const_lv5_0);
}

void maxPooling::thread_tmp_9_cast_fu_581_p1() {
    tmp_9_cast_fu_581_p1 = esl_zext<13,6>(tmp_7_fu_576_p2.read());
}

void maxPooling::thread_tmp_9_fu_512_p2() {
    tmp_9_fu_512_p2 = (!p_shl2_fu_496_p1.read().is_01() || !p_shl3_fu_508_p1.read().is_01())? sc_lv<64>(): (sc_biguint<64>(p_shl2_fu_496_p1.read()) - sc_biguint<64>(p_shl3_fu_508_p1.read()));
}

void maxPooling::thread_tmp_fu_365_p3() {
    tmp_fu_365_p3 = esl_concat<12,7>(tmp_1_fu_359_p2.read(), ap_const_lv7_0);
}

void maxPooling::thread_tmp_i_cast_14_fu_738_p1() {
    tmp_i_cast_14_fu_738_p1 = esl_zext<5,2>(j_i_reg_314.read());
}

void maxPooling::thread_tmp_i_cast_fu_677_p1() {
    tmp_i_cast_fu_677_p1 = esl_zext<5,2>(i_i_reg_279.read());
}

void maxPooling::thread_tmp_s_fu_530_p3() {
    tmp_s_fu_530_p3 = esl_concat<5,1>(j6_reg_224.read(), ap_const_lv1_0);
}

void maxPooling::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_fu_331_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond3_fu_343_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond5_fu_395_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_446_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(exitcond4_fu_458_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(exitcond6_fu_518_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_542_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(exitcond_fu_621_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(exitcond3_i_fu_665_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 4096 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && esl_seteq<1,1,1>(exitcond_i_fu_726_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_state14;
            }
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<14>) ("XXXXXXXXXXXXXX");
            break;
    }
}

}

